#!/usr/bin/env python3
"""Strict Fail-Closed Migration Dependency Lock Generator.

Resolves dependency lock file for Finance Intelligence Staging Migration Runner.
FAILS IMMEDIATELY (exit code 1) on any HTTP 404, missing hashes, or invalid package metadata.
"""

import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

# Direct dependencies authority
MIGRATION_PACKAGES = [
    ("alembic", "1.13.2"),
    ("SQLAlchemy", "2.0.31"),
    ("greenlet", "3.0.3"),
    ("cloud-sql-python-connector", "1.9.2"),
    ("google-cloud-secret-manager", "2.9.2"),
    ("pydantic-settings", "2.3.4"),
    ("Mako", "1.3.5"),
    ("typing_extensions", "4.12.2"),
    ("aiohttp", "3.9.5"),
    ("google-api-core", "2.19.1"),
    ("google-auth", "2.32.0"),
    ("requests", "2.32.3"),
    ("pg8000", "1.31.2"),
    ("scramp", "1.4.5"),
    ("python-dateutil", "2.9.0.post0"),
    ("six", "1.16.0"),
    ("asn1crypto", "1.5.1"),
    ("grpc-google-iam-v1", "0.13.1"),
    ("proto-plus", "1.24.0"),
    ("protobuf", "4.25.3"),
    ("pydantic", "2.8.2"),
    ("python-dotenv", "1.0.1"),
    ("attrs", "23.2.0"),
    ("multidict", "6.0.5"),
    ("yarl", "1.9.4"),
    ("frozenlist", "1.4.1"),
    ("aiosignal", "1.3.1"),
    ("googleapis-common-protos", "1.63.2"),
    ("cachetools", "5.4.0"),
    ("pyasn1-modules", "0.4.0"),
    ("rsa", "4.9"),
    ("charset-normalizer", "3.3.2"),
    ("idna", "3.7"),
    ("urllib3", "2.2.2"),
    ("certifi", "2024.7.4"),
    ("grpcio", "1.64.1"),
    ("grpcio-status", "1.64.1"),
    ("pydantic_core", "2.20.1"),
    ("annotated-types", "0.7.0"),
    ("pyasn1", "0.6.0"),
]

# Nonexistent/hallucinated packages that MUST be rejected if present
FORBIDDEN_PACKAGES = {
    "google-cloud-secret-manager-v1",
    "scamper",
}


def generate_lock(output_path: Path) -> None:
    header = """# Autogenerated Finance Intelligence Migration Runner Dependency Lock File
# Direct dependencies from requirements-migration.in
# Target Platform: linux/amd64 (Python 3.11)
"""
    output_blocks = [header]

    for pkg, ver in MIGRATION_PACKAGES:
        if pkg in FORBIDDEN_PACKAGES:
            raise RuntimeError(f"LOCK GENERATOR ERROR: Forbidden nonexistent package requested: {pkg}")

        url = f"https://pypi.org/pypi/{pkg}/{ver}/json"
        req = urllib.request.Request(url, headers={"User-Agent": "pypi-checker/1.0"})

        try:
            res = urllib.request.urlopen(req)
            data = json.loads(res.read())
        except urllib.error.HTTPError as e:
            raise RuntimeError(f"FAIL_CLOSED_LOCK_GENERATOR_ERROR: HTTP {e.code} fetching metadata for {pkg}=={ver}")
        except Exception as e:
            raise RuntimeError(f"FAIL_CLOSED_LOCK_GENERATOR_ERROR: Failed fetching metadata for {pkg}=={ver}: {e}")

        urls_info = data.get("urls", [])
        if not urls_info:
            raise RuntimeError(f"FAIL_CLOSED_LOCK_GENERATOR_ERROR: Zero artifacts found for {pkg}=={ver}")

        hashes = set()
        for u in urls_info:
            sha256 = u.get("digests", {}).get("sha256")
            if not sha256 or len(sha256) != 64:
                raise RuntimeError(f"FAIL_CLOSED_LOCK_GENERATOR_ERROR: Invalid SHA-256 for {pkg}=={ver}: {sha256}")
            hashes.add(sha256)

        sorted_hashes = sorted(list(hashes))
        block_lines = [f"{pkg}=={ver} \\"]
        for idx, h in enumerate(sorted_hashes):
            sep = " \\" if idx < len(sorted_hashes) - 1 else ""
            block_lines.append(f"    --hash=sha256:{h}{sep}")
        output_blocks.append("\n".join(block_lines))

    final_content = "\n".join(output_blocks) + "\n"
    output_path.write_text(final_content)
    print(f"SUCCESS: Generated lock file {output_path} with {len(MIGRATION_PACKAGES)} packages.")


if __name__ == "__main__":
    repo_root = Path(__file__).resolve().parent.parent
    lock_file = repo_root / "services" / "api" / "requirements-migration.lock"
    try:
        generate_lock(lock_file)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)
